bot.name = realurban_bot
bot.token = 6317568902:AAHWxR34H9hsMIUTTnwGWnGIG6B9X5YhWKU
#??? ?????? 6342761132:AAFKzYuKd2twYCDUCy2Cop1P0Y2EEdynLc0 // bot_4_tests
#???? 6317568902:AAHWxR34H9hsMIUTTnwGWnGIG6B9X5YhWKU // realurban_bot

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://77.232.131.243:5432/default_db
spring.datasource.username=gen_user
spring.datasource.password=daniilzz

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true