bot.name = realurban_bot
bot.token = -----

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://77.232.131.243:5432/default_db
spring.datasource.username=-----
spring.datasource.password=-----

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
